//this file was generated by ../../../../scripts/onnx_generator/OperatorSets.py

#include "operators/operator_set.h"

extern operator_set_opname opname_operator__ai_onnx__matmul;
extern operator_set_opname opname_operator__ai_onnx__identity;
extern operator_set_opname opname_operator__ai_onnx__maxpool;
extern operator_set_opname opname_operator__ai_onnx__transpose;
extern operator_set_opname opname_operator__ai_onnx__clip;
extern operator_set_opname opname_operator__ai_onnx__elu;
extern operator_set_opname opname_operator__ai_onnx__relu;
extern operator_set_opname opname_operator__ai_onnx__conv;
extern operator_set_opname opname_operator__ai_onnx__argmax;
extern operator_set_opname opname_operator__ai_onnx__add;
extern operator_set_opname opname_operator__ai_onnx__and;
extern operator_set_opname opname_operator__ai_onnx__leakyrelu;
extern operator_set_opname opname_operator__ai_onnx__reshape;
extern operator_set_opname opname_operator__ai_onnx__globalaveragepool;
extern operator_set_opname opname_operator__ai_onnx__mul;
extern operator_set_opname opname_operator__ai_onnx__constant;
extern operator_set_opname opname_operator__ai_onnx__batchnormalization;
extern operator_set_opname opname_operator__ai_onnx__sigmoid;
extern operator_set_opname opname_operator__ai_onnx__softmax;
extern operator_set_opname opname_operator__ai_onnx__convtranspose;
extern operator_set_opname opname_operator__ai_onnx__cos;
extern operator_set_opname opname_operator__ai_onnx__sin;
extern operator_set_opname opname_operator__ai_onnx__sqrt;
extern operator_set_opname opname_operator__ai_onnx__neg;
extern operator_set_opname opname_operator__ai_onnx__isnan;
extern operator_set_opname opname_operator__ai_onnx__div;
extern operator_set_opname opname_operator__ai_onnx__pow;
extern operator_set_opname opname_operator__ai_onnx__equal;
extern operator_set_opname opname_operator__ai_onnx__lessorequal;
extern operator_set_opname opname_operator__ai_onnx__where;
extern operator_set_opname opname_operator__ai_onnx__shape;
extern operator_set_opname opname_operator__ai_onnx__flatten;
extern operator_set_opname opname_operator__ai_onnx__unsqueeze;
extern operator_set_opname opname_operator__ai_onnx__expand;
extern operator_set_opname opname_operator__ai_onnx__cast;
extern operator_set_opname opname_operator__ai_onnx__concat;
extern operator_set_opname opname_operator__ai_onnx__gather;
extern operator_set_opname opname_operator__ai_onnx__slice;
extern operator_set_opname opname_operator__ai_onnx__constantofshape;
extern operator_set_opname opname_operator__ai_onnx__range;
extern operator_set_opname opname_operator__ai_onnx__reducemean;

operator_set_opdomain opdomain_operator__ai_onnx = {
    .name = "ai.onnx",
    .opnames = {
        &opname_operator__ai_onnx__matmul,
        &opname_operator__ai_onnx__identity,
        &opname_operator__ai_onnx__maxpool,
        &opname_operator__ai_onnx__transpose,
        &opname_operator__ai_onnx__clip,
        &opname_operator__ai_onnx__elu,
        &opname_operator__ai_onnx__relu,
        &opname_operator__ai_onnx__conv,
        &opname_operator__ai_onnx__argmax,
        &opname_operator__ai_onnx__add,
        &opname_operator__ai_onnx__and,
        &opname_operator__ai_onnx__leakyrelu,
        &opname_operator__ai_onnx__reshape,
        &opname_operator__ai_onnx__globalaveragepool,
        &opname_operator__ai_onnx__mul,
        &opname_operator__ai_onnx__constant,
        &opname_operator__ai_onnx__batchnormalization,
        &opname_operator__ai_onnx__sigmoid,
        &opname_operator__ai_onnx__softmax,
        &opname_operator__ai_onnx__convtranspose,
        &opname_operator__ai_onnx__cos,
        &opname_operator__ai_onnx__sin,
        &opname_operator__ai_onnx__sqrt,
        &opname_operator__ai_onnx__neg,
        &opname_operator__ai_onnx__isnan,
        &opname_operator__ai_onnx__div,
        &opname_operator__ai_onnx__pow,
        &opname_operator__ai_onnx__equal,
        &opname_operator__ai_onnx__lessorequal,
        &opname_operator__ai_onnx__where,
        &opname_operator__ai_onnx__shape,
        &opname_operator__ai_onnx__flatten,
        &opname_operator__ai_onnx__unsqueeze,
        &opname_operator__ai_onnx__expand,
        &opname_operator__ai_onnx__cast,
        &opname_operator__ai_onnx__concat,
        &opname_operator__ai_onnx__gather,
        &opname_operator__ai_onnx__slice,
        &opname_operator__ai_onnx__constantofshape,
        &opname_operator__ai_onnx__range,
        &opname_operator__ai_onnx__reducemean,
        NULL
    }
};