//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__and__7.h"
#include "tracing.h"
#include "utils.h"

operator_status
execute_operator__ai_onnx__and__7__T_tensor_float(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    Onnx__TensorProto *i_A = searchInputByName(ctx, 0);
    Onnx__TensorProto *i_B = searchInputByName(ctx, 1);

    TRACE_TENSOR(2, true, i_A);
    TRACE_TENSOR(2, true, i_B);

    Onnx__TensorProto *o_C = searchOutputByName(ctx, 0);

    TRACE_TENSOR(2, true, o_C);

    /* Perform element-wise bitwise AND with broadcasting */
    size_t total_elements = 1;
    for (int d = 0; d < o_C->n_dims; d++) {
        total_elements *= o_C->dims[d];
    }

    for (size_t i = 0; i < total_elements; i++) {
        size_t idx_A = i;
        size_t idx_B = i;

        /* Simple broadcasting: if dimensions don't match, assume broadcasting along the first dimension */
        if (i_A->n_dims != i_B->n_dims) {
            if (i_B->n_dims == 1) {
                idx_B = i % i_B->dims[0];
            } else if (i_A->n_dims == 1) {
                idx_A = i % i_A->dims[0];
            } else {
                /* For more complex broadcasting, this is a placeholder */
                /* In a full implementation, compute proper broadcast indices */
                idx_A = i;
                idx_B = i;
            }
        }

        /* Bitwise AND for float (treating as bit representation) */
        uint32_t a_bits = *(uint32_t*)&i_A->float_data[idx_A];
        uint32_t b_bits = *(uint32_t*)&i_B->float_data[idx_B];
        uint32_t result_bits = a_bits & b_bits;
        o_C->float_data[i] = *(float*)&result_bits;
    }

    TRACE_EXIT(1);

    return OP_OK;
}