//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__matmul__9.h"
#include "matmul_kernel.h"
#include "tracing.h"
#include "utils.h"
#include "op_utils.h"

operator_status
execute_operator__ai_onnx__matmul__9__T_tensor_int64(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    Onnx__TensorProto *i_A = searchInputByName(ctx, 0);
    Onnx__TensorProto *i_B = searchInputByName(ctx, 1);

    TRACE_TENSOR(2, true, i_A);
    TRACE_TENSOR(2, true, i_B);

    Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    /* Skip if output tensor is empty (has 0-dim) */
    if (tensor_is_empty(o_Y)) return OP_OK;

    TRACE_TENSOR(2, true, o_Y);

    matmul_int64(i_A->int64_data, i_A->dims[0], i_A->dims[1],
                 i_B->int64_data, i_B->dims[1],
                 o_Y->int64_data);

    TRACE_EXIT(1);

    return OP_OK;
}
