//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__matmul__9.h"
#include "tracing.h"
#include "utils.h"

operator_status
prepare_operator__ai_onnx__matmul__9(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    Onnx__TensorProto *i_A = searchInputByName(ctx, 0);
    Onnx__TensorProto *i_B = searchInputByName(ctx, 1);

    TRACE_TENSOR(2, true, i_A);
    TRACE_TENSOR(2, true, i_B);

    Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // context_operator__ai_onnx__matmul__9 *op_ctx = NULL;
    // op_ctx = malloc(sizeof(context_operator__ai_onnx__matmul__9));
    // TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */

    // Support for arbitrary dimensions with broadcasting for batch dimensions
    TRACE_FATAL(0, i_A->n_dims < 2 || i_B->n_dims < 2, "MatMul requires at least 2 dimensions");

    int64_t n_dims_Y = (i_A->n_dims > i_B->n_dims) ? i_A->n_dims : i_B->n_dims;
    int64_t a_inner = i_A->dims[i_A->n_dims - 1];
    int64_t b_inner = i_B->dims[i_B->n_dims - 2];
    TRACE_FATAL(0, a_inner != b_inner, "Inner dimensions must match for MatMul");

    o_Y->has_raw_data = 0;
    o_Y->n_dims = n_dims_Y;
    o_Y->dims = malloc(o_Y->n_dims * sizeof(int64_t));
    o_Y->data_type = i_A->data_type;

    // Compute broadcasted batch dimensions
    for (int64_t i = 0; i < n_dims_Y - 2; ++i) {
        int64_t a_dim = (i < i_A->n_dims - 2) ? i_A->dims[i] : 1;
        int64_t b_dim = (i < i_B->n_dims - 2) ? i_B->dims[i] : 1;
        TRACE_FATAL(0, (a_dim != b_dim) && (a_dim != 1) && (b_dim != 1), "Batch dimensions are not broadcastable");
        o_Y->dims[i] = (a_dim > b_dim) ? a_dim : b_dim;
    }

    // Set the matrix dimensions
    o_Y->dims[n_dims_Y - 2] = i_A->dims[i_A->n_dims - 2];
    o_Y->dims[n_dims_Y - 1] = i_B->dims[i_B->n_dims - 1];

    /* MALLOC OUTPUT TENSORS HERE */

    mallocTensorData(o_Y);

    TRACE_TENSOR(2, true, o_Y);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    ctx->executer = resolve_operator__ai_onnx__matmul__9(ctx);
    // ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    // return OP_ENOSYS;
    return OP_OK;
}